name: Shell Commands

on: [push]

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: simple js action
        id: greet
        uses: 728-2y/action-test@main
        with:
          who-to-greet: john
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
