name: actions workflow

on: 
  # 通过发送api请求，检测到请求触发
  # 参考文档 https://docs.github.com/cn/rest/repos/repos#create-a-repository-dispatch-event
  # repository_dispatch:
  #  types: [build]
  # 定时任务
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"

  # push 动作
  #push:
  #  branches:
  #    - "master"
  #    - "feature/*" #　matches feature/featA, feature/featB
                    #  doestn't match featrue/feat/a
  #  tags:
  #    - "v1.*"
    
  pull_request:
    types:
      - "closed"
      - "assigned"
      - "opened"
      - "reopened"

jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls -a
      - name: checkout
        uses: actions/checkout@v1
      - name: list files after checkout
        run: |
          pwd
          ls -a
      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: yushan
      - name: log greeting time
        run: echo "${{steps.greet.outputs.time}}"
